# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0003_auto_20170322_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ends_at', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fatura',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('length', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Plano',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Plan'),
        ),
        migrations.AddField(
            model_name='bill',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Truck'),
        ),
    ]
