# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_checkin_formatted_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
