# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name_plural': 'Food Trucks'},
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='onwer_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='pin',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
