# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:49
from __future__ import unicode_literals

import apps.personas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='avatar',
            field=models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to=apps.personas.utils.truck_path),
        ),
    ]
